services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: infotecstask
    environment:
      POSTGRES_DB: infotecsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      postgres
      -c listen_addresses='*'
      -c password_encryption=scram-sha-256
    restart: unless-stopped 
volumes:
  postgres_data:

